export const RECEIVE_POPULAR_MOVIES = "RECEIVE_POPULAR_MOVIES";
export const RECEIVE_POPULAR_MOVIES_ERROR = "RECEIVE_POPULAR_MOVIES_ERROR";
export const RECEIVE_POSTER = "RECEIVE_POSTER";
export const RECEIVE_POSTER_ERROR = "RECEIVE_POSTER_ERROR";